#!/usr/bin/env bash

if [ $# -eq 2 ] || [ $# -eq 3 ]; then
    before="$1"; shift
    after="$1"; shift
    cat "$@" | prepend "$before" | append "$after"
else
	echo "Usage: $0 <before> <after> [file]" >&2
	exit 1
fi
